### ISSUE TITLE
[test scenario] slashing - verify sector termination fee is levied upon 14 consecutive missed proving windows

### ISSUE THREAD

**Issue by yusefnapora** [filecoin-project/oni#120]
**Describe the test scenario.**

Part of slashing epic (#21) - see [slashing google doc](https://docs.google.com/document/d/1m9NU-NfaFqg8SdwMm9hf-1wzPHnFC-9PJSub8ho9R2E/edit#) for more info.

If a sector is faulted for 14 consecutive proving windows, or if a miner declares the sector to be terminated, they get hit with a Termination Fee (in addition to the Fault Fees and whatever Sector Penalties they might have accrued during the fault).

**Provide any background and technical implementation details.**

We should test both ways of reaching the terminal state:

- wait 14 proving windows and check that the sector was marked as terminated and the fee was applied
- have the miner declare the sector terminated

**What should we measure?**

- verify that the sector was marked as terminated in chain state
- verify that the miner was slashed by the termination fee amount (plus other penalties that stack up during the fault)

**Discomfort factor (0-10).**

 

**Additional remarks.**

**Comment by raulk** [comment]
@nonsense I'm assigning this to you since you're owning most test cases related to sector proving. @yusefnapora can help sort out the slashing consequences.
