### ISSUE TITLE
initial test driver MVP (importing seed state via a genesis block + apply messages)

### ISSUE THREAD

**Issue by raulk** [filecoin-project/oni#165]
# Goal

Assume a test vector exists that encodes:

- input state, as a map of `address.Address => []byte` (where []byte is the serialised state of the actor) that can be transformed into the state tree HAMT.
- a message to apply atop that seed state.

The goal of this task is to produce an MVP of the Lotus test driver that takes the test vector, and:

1. tries to use the [genesis block generation utilities](https://github.com/filecoin-project/lotus/tree/master/chain/gen/genesis) to import our custom initial state (as defined by the test vector) into a fresh StateTree.
2. applies the message onto that StateTree.

# Notes

There's lots of stuff we can reuse/repurpose from Chain Validation, especially the components on the Lotus side (appliers, state wrapper, etc.)

Refer to the `chain/validation` package: https://github.com/filecoin-project/lotus/tree/master/chain/validation.

**Comment by nonsense** [comment]
@raulk I think we can consider this done.

It'd be nice to do the end-to-end test as part of CI:
1. Generate test vector from `suite-messages` command for example (and all upcoming test vector suites)
2. Pipe output from 1. to `exec-lotus` and make sure that test vectors are successful (i.e. compare post root cids).

**Comment by nonsense** [comment]
Since we added end-to-end tests as part of CI, I think this can be marked as done.
