### ISSUE TITLE
switch test vector state binary fields to gzip + base64; try brotli

### ISSUE THREAD

**Issue by raulk** [filecoin-project/oni#183]
This allows for shorter test vectors. We could also try Brotli instead of gzip, should give us a better compression ratio.

Tasks:

- [x] Switch to gzip (after: gzip + hex).
- [x] Switch to base64 (after: gzip + base64).
- [ ] Try Brotli (after: Brotli + base64).

Re: Brotli, I was inspired by https://dropbox.tech/infrastructure/-broccoli--syncing-faster-by-syncing-less.

**Comment by alanshaw** [comment]
In our colo call today we decided the size reduction with [brotli+base64](https://github.com/filecoin-project/oni/pull/234) was not worth the additional UX/DX for an additional saving of ~3% over [gzip+base64](https://github.com/filecoin-project/oni/pull/233).
