### ISSUE TITLE
generate message-class test vectors based on `chain-validation` project

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/oni#194]
As a follow up to https://github.com/filecoin-project/oni/pull/181, we should review and convert all tests into test vectors, if they make sense:

https://github.com/filecoin-project/chain-validation/tree/master/suites

TODO:
- [x] generate test vectors for the messages/create-actor suite
- [x] generate test vectors for the messages/message-application suite
- [x] generate test vectors for the messages/multisig suite
- [x] generate test vectors for the messages/nested suite
- [x] generate test vectors for the messages/paych suite
- [x] generate test vectors for the messages/transfer suite

**Comment by raulk** [comment]
@alanshaw @willscott help requested here to divide and conquer! Comment if you'd like to pick up the migration of an item here, and ping @nonsense to align.

**Comment by alanshaw** [comment]
I'm going to take a stab at `messages/multisig`

**Comment by nonsense** [comment]
I am picking up payment channel tests (updated the description).

**Comment by nonsense** [comment]
Will be picking up the messages/transfer suite tomorrow.

**Comment by nonsense** [comment]
Starting `messages/nested` now.

**Comment by raulk** [comment]
I extracted the tipset-class vectors to https://github.com/filecoin-project/oni/issues/220. So now this issue is only about message-class vectors, and it can be closed ;-)
