### ISSUE TITLE
templating API for message-class test vectors

### ISSUE THREAD

**Issue by raulk** [filecoin-project/oni#206]
Generation scripts seem to have a common structure, revolving around three main phases:

- precondition state preparation (creating accounts and such)
- creating and applying messages
- semantically asserting the result

Currently, we are manually capturing the prestate, post state, and populating/genearting the test vectors. There's opportunity to be DRY and encapsulate some of that scaffolding into a template API.

**Comment by raulk** [comment]
@alanshaw @nonsense assigning you here because there was some initial DRYing done in:

https://github.com/filecoin-project/oni/pull/217
https://github.com/filecoin-project/oni/pull/212
https://github.com/filecoin-project/oni/pull/211

I have some further ideas with a template-based functional API that I'll prototype today, and then we can see if we want to go in that direction. SGTY?

**Comment by nonsense** [comment]
@raulk not sure what you have in mind with this one, but I suggest we postpone until we have 1-2 tipset tests where we apply multiple blocks on multiple epochs. It would make it easier to reason about the abstractions we need.

**Comment by raulk** [comment]
This was fixed in #229.
